"""Single source of truth for API error ``code`` values (observability / alerting)."""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_CLIENT_ID = "INVALID_CLIENT_ID"
    UNAUTHORIZED = "UNAUTHORIZED"
    NOT_FOUND = "NOT_FOUND"
    ENTITY_TENANT_MISMATCH = "ENTITY_TENANT_MISMATCH"
    INVALID_OPERATION = "INVALID_OPERATION"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    CLIENT_NAME_ALREADY_TAKEN = "CLIENT_NAME_ALREADY_TAKEN"
    FORBIDDEN = "FORBIDDEN"
    INTERNAL_MISUSE = "INTERNAL_MISUSE"
    VALIDATION_ERROR = "VALIDATION_ERROR"

    CLEAR_DATA_DISABLED = "CLEAR_DATA_DISABLED"
    INVALID_CONFIRMATION = "INVALID_CONFIRMATION"

    ADS_REPORT_CSV_NOT_FOUND = "ADS_REPORT_CSV_NOT_FOUND"
    CSV_FILE_NOT_FOUND = "CSV_FILE_NOT_FOUND"
    INVALID_CSV_COLUMNS = "INVALID_CSV_COLUMNS"
    CSV_NOT_LOADED = "CSV_NOT_LOADED"
    CSV_TOO_LARGE = "CSV_TOO_LARGE"
    CSV_ENCODING = "CSV_ENCODING"
    CSV_HEADER_MISSING = "CSV_HEADER_MISSING"
    CSV_NO_DATA = "CSV_NO_DATA"
    CSV_UNSUPPORTED_FORMAT = "CSV_UNSUPPORTED_FORMAT"
    CSV_DELIMITER_MISMATCH = "CSV_DELIMITER_MISMATCH"

    INVALID_METRIC_SAVE = "INVALID_METRIC_SAVE"
    INVALID_INTEGRATION_UPDATE = "INVALID_INTEGRATION_UPDATE"
